module.exports = [
  'NIMBUS-OS v4.0.2 | Sistema Activo',
  'Inicializando módulos de supervivencia...',
  'Verificando integridad del sistema...',
  'Escaneando anomalías en la Zona...',
  'Monitoreando signos vitales de ciudadanos',
  'Conexión satelital establecida [GPS_ACTIVE]',
  'Buscando firmas de emisiones de psique...',
  'Sincronizando base de datos de suministros',
  'Calculando trayectorias de radioactividad',
  'Analizando niveles de toxicidad ambiental...',
  'Detectando actividad hostil cercana...',
  'Revisando estado de equipo táctico...',
  'Actualizando registros de exploración...',
  'Procesando datos de supervivientes...',
  'Rastreando señales de auxilio...',
  'Compilando rutas seguras disponibles...',
  'Escaneo térmico en progreso...',
  'Verificando filtros de respiración...',
  'Monitoreando consumo de recursos...',
  'Chequeo de estabilidad mental en curso...',
  'Detectando fluctuaciones electromagnéticas...',
  'Optimizando consumo energético...',
  'Sincronizando con red NIMBUS...',
  'Analizando patrones de movimiento...',
  'Revisando estado de armamento...',
  'Calibrando sensores de proximidad...',
  'Escaneando estructuras colapsadas...',
  'Filtrando interferencias de señal...',
  'Monitoreando ritmo cardíaco...',
  'Detectando niveles de fatiga...',
  'Buscando rutas de evacuación...',
  'Actualizando mapa táctico...',
  'Registrando actividad reciente...',
  'Detectando posibles amenazas biológicas...',
  'Escaneo acústico en progreso...',
  'Verificando presión atmosférica...',
  'Analizando calidad del aire...',
  'Detectando fuentes de calor...',
  'Sincronización parcial completada...',
  'Error leve detectado | Reintentando...',
  'Señal inestable | Ajustando frecuencia...',
  'Modo ahorro de energía activado...',
  'Reestableciendo conexión perdida...',
  'Buscando nodos de comunicación...',
  'Interfaz neural en espera...',
  'Procesando comandos del usuario...',
  'Actualizando firmware del sistema...',
  'Acceso restringido detectado...',
  'Escaneo completo en progreso...',
  'Validando credenciales de usuario...',
  'Monitoreando entorno inmediato...',
  'Detección de movimiento confirmada...',
  'Análisis predictivo en curso...',
  'Base de datos incompleta...',
  'Abandona toda esperanza...',
  'Recuperando archivos dañados...',
  'Modo exploración activo...',
  'Modo sigilo recomendado...',
  'Riesgo elevado detectado...',
  'Zona inestable identificada...',
  'Anomalía catalogada parcialmente...',
  'Interferencia psíquica detectada...',
  'Advertencia: niveles críticos...'
];